<h4>Editar Producto</h4>
    
<form method ="POST" action="editar">
    <label for="Id">ID del Producto:</label>
    <input type="text" id="Id" name="id" required>

    <label for="Producto">Nuevo Producto:</label>
    <input type="text" id="producto"  name = "producto" required>
    
    <label for="Precio">Nuevo Precio:</label>
    <input type="number" id="precio" name="precio" required>

    <label for="Categoria">Nueva Categoría:</label>
    <select id="categoria" name="categoria" required>
        <option value="Celular">Celular</option>
        <option value="Audio">Audio</option>
        <option value="Accesorio">Accesorio</option>
    </select>
    <button type ="submit" class="btn btn-warning">Actualizar </button>
</form>