<scripth src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous"></script>
<div class="container">
<footer class="footer fixed-bottom bg-dark text-white">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <p>&copy; 2023 Celus-Tandil</p>
                </div>
                <div class="col-sm-6 text-right">
                    <a href="#" class="text-decoration-none text-white">Términos y Condiciones</a>
                    <span class="mx-3">|</span>
                    <a href="#" class="text-decoration-none text-white">Política de Privacidad</a>
                    <span class="mx-3">|</span>
                    <a href="#" class="text-decoration-none text-white">Instagram</a>
                    <span class="mx-3">|</span>
                    <a href="#" class="text-decoration-none text-white">Twitter</a>
                  </div>
            </div>
        </div>
    </footer>

    <!-- Agrega enlaces a las bibliotecas de Font Awesome si deseas usar los íconos de redes sociales -->
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <!-- Agrega enlaces a los archivos JavaScript de Bootstrap y jQuery si los necesitas -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
</div>
</body>
</html>

