<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <title>TUDAI - Lista de tareas</title>
</head>
<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand mx-4" href="home">Celus-Tandil</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="home">Home <span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="lista">Lista<span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
            <?php if (isset($_SESSION['USER_ID'])) : ?>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="logout">Logout (<?= $_SESSION['USERNAME'] ?>)</a>
            </li>
            <?php else : ?>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="login">Login</a>
              </li>
            <?php endif ?>
          </li>
        </ul>
      </div>
    </nav>
  </header>
    <main class="container mt-3">
</body>

