<?php require './templates/header.phtml';?>
<link rel="stylesheet" href="/css/style.css">
<main>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm2 row-cols-md-2 g3">
            <div class="col">
                <div class="card shadow-sm">
                    <img src="img/Celular.jpg" alt="imagen de celular">
                    <div class="card-body">
                        <h5 class="card-title">Celulares</h5>
                            <div class="btn-group text-decoration-none">
                                <a href="lista"class="btn btn-primary text-decoration-none">Ver Mas</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card shadow-sm">
                    <img src="img/Parlante.jpg" alt="imagen de celular">
                    <div class="card-body">
                        <h5 class="card-title">Audio</h5>
                            <div class="btn-group text-decoration-none">
                                <a href="lista"class="btn btn-primary text-decoration-none">Ver Mas</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<?php require './templates/footer.phtml';?>
